const stories={threadly:{label:'CURRENTLY BUILDING / THREADLY',title:'Finding the right conversation.',body:`<p>Threadly is an AI GTM copilot we’re building to help businesses find relevant online conversations around the problems their products solve.</p><h4>The idea</h4><p>Start with a product, the problem it solves, and the people it’s meant for. Find relevant discussions on Reddit and LinkedIn, understand the context, and help draft a useful response.</p><h4>Where it stands</h4><p>I’m working on the GTM strategy. The product is in development: discovery, human-reviewed responses, and tracking interested prospects are part of the planned journey.</p><p class="muted">A relevant conversation is a starting point, not automatically a qualified lead.</p>`},stockflow:{label:'AI IN BUSINESS / STOCKFLOW',title:'From stock on a shelf to a clearer picture.',body:`<p>I built StockFlow for my AI in Business project, using sports retail as the setting for an inventory and procurement system.</p><h4>What the project covers</h4><p>A catalog of 15 SKUs, stock movements, inventory valuation, low-stock alerts, demand forecasts, and reorder recommendations.</p><p>The procurement side brings together suppliers, purchase orders, goods receiving, invoices, and payments. Reports connect the stock picture with purchasing decisions.</p><h4>Why this project</h4><p>It gave me a way to explore how inventory management, replenishment, and procurement fit together in one workflow.</p><a class="pill" href="https://stockflow-inventory-gfw0.onrender.com/" target="_blank" rel="noopener">Explore StockFlow</a>`},taara:{label:'TEAM TAARA / DLF CYBERHUB',title:'₹97,000. One day. A team effort.',body:`<p>We brought crystals and gemstones to the Dropshipping Mela at DLF CyberHub. Our first sale came at 10:32 AM. By 2:15 PM, we had made ₹7,500.</p><h4>Changing our approach</h4><p>We stepped up our outreach: approaching people, starting conversations, pitching, and explaining the products. Slowly, sales began to pick up.</p><p>When we closed the stall at 10:30 PM, the team had generated <strong>₹97,000 in revenue</strong>.</p><h4>What stayed with me</h4><p>How much a day can change when you change your approach and keep going.</p><p class="muted">Revenue is the team’s total sales for the day, not profit.</p>`}};
const dialog=document.querySelector('dialog');document.querySelectorAll('[data-story]').forEach(b=>b.addEventListener('click',()=>{const s=stories[b.dataset.story];document.querySelector('#story-content').innerHTML=`<div class="section-label">${s.label}</div><h2>${s.title}</h2>${s.body}`;dialog.showModal();document.body.style.overflow='hidden'}));dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>document.body.style.overflow='');dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
// Short personal notes, not a live news feed. Edit this list as the portfolio grows.
const notes = [
  'Curiosity is always in stock.',
  'Currently replenishing my supply of questions.',
  'A good question is worth the detour.',
  'My kind of puzzle: what happens between order and delivery?',
  'Learning the route by getting on the ground.',
  'Some ideas need a spreadsheet. Some need a conversation.',
  'Cricket taught me to stay in the game.',
  'Still curious about what happens behind the shelf.',
  'Small details. Surprisingly big consequences.',
  'There is usually a better question to ask.',
  'Threadly started with a question about conversations.',
  'StockFlow: turning inventory questions into a project.',
  'One stall taught us a lot in one day.',
  'A slow afternoon does not decide the whole day.',
  'The last mile still needs a first step.',
  'Learning, with a few wrong turns included.',
  'Ideas in transit. Questions arriving daily.',
  'More curious than yesterday.'
];
const noteText = document.querySelector('#note-text');
const notePause = document.querySelector('#note-pause');
const motionPreference = matchMedia('(prefers-reduced-motion: reduce)');
let noteIndex = 0, notesPaused = motionPreference.matches;
function updatePause(){notePause.textContent=notesPaused?'Play':'Pause';notePause.setAttribute('aria-label',notesPaused?'Play rotating notes':'Pause rotating notes');}
function nextNote(){noteIndex=(noteIndex+1)%notes.length;noteText.textContent=notes[noteIndex];if(!motionPreference.matches)noteText.animate([{opacity:0,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:350});}
notePause.onclick=()=>{notesPaused=!notesPaused;updatePause()};
document.querySelector('#note-next').onclick=nextNote;
updatePause();
setInterval(()=>{if(!notesPaused&&!document.hidden&&!dialog.open)nextNote()},6500);
motionPreference.addEventListener('change',e=>{if(e.matches){notesPaused=true;updatePause()}});
async function warehouse(){const THREE=await import('./assets/three.module.js');const el=document.querySelector('#scene');const scene=new THREE.Scene();const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0xf8f8f4,0);el.appendChild(renderer.domElement);const camera=new THREE.PerspectiveCamera(31,1,.1,100);camera.position.set(6,7.5,19);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0xffffff,0xb1b7a0,3));const sun=new THREE.DirectionalLight(0xfff4df,4);sun.position.set(-6,12,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-13,right:13,top:13,bottom:-13});sun.shadow.normalBias=.03;scene.add(sun);
const model=new THREE.Group();scene.add(model);const mats={ivory:new THREE.MeshStandardMaterial({color:0xe9e6da,roughness:.85}),roof:new THREE.MeshStandardMaterial({color:0x426252,roughness:.65}),green:new THREE.MeshStandardMaterial({color:0x294d40,roughness:.45}),dark:new THREE.MeshStandardMaterial({color:0x29362f,roughness:.8}),concrete:new THREE.MeshStandardMaterial({color:0xd4d5c9,roughness:1}),asphalt:new THREE.MeshStandardMaterial({color:0xadb3a7,roughness:1}),wood:new THREE.MeshStandardMaterial({color:0xb99059,roughness:1}),box:new THREE.MeshStandardMaterial({color:0xc6a97a,roughness:1}),white:new THREE.MeshStandardMaterial({color:0xf9f6e8,roughness:.7}),glass:new THREE.MeshStandardMaterial({color:0x45616a,roughness:.15,metalness:.3}),black:new THREE.MeshStandardMaterial({color:0x202923,roughness:.9})};
function box(w,h,d,x,y,z,mat,parent=model){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}function cyl(r,h,x,y,z,mat,parent=model){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,24),mat);m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m}function label(text,w,h,x,y,z,size=60,parent=model){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#294d40';ctx.fillRect(0,0,512,128);ctx.fillStyle='#fffdf1';ctx.font=`500 ${size}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,64);const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(c)}));mesh.position.set(x,y,z);parent.add(mesh);return mesh}
box(11,.22,8,0,-.15,0,mats.concrete);box(10,.025,3.2,0,-.025,2.2,mats.asphalt);for(let i=-4;i<5;i+=1.5)box(.7,.018,.055,i,0,3.5,mats.white);
box(8,2.6,.15,0,1.3,-2,mats.ivory);box(.16,2.6,3.6,-4,1.3,-.3,mats.ivory);box(.16,2.6,3.6,4,1.3,-.3,mats.ivory);box(8,.25,3.8,0,2.7,-.25,mats.roof);for(let i=-4;i<=4;i+=.24)box(.035,.05,3.8,i,2.855,-.25,mats.green);box(8,.57,.18,0,2.3,1.5,mats.ivory);box(8,.12,.4,0,1.99,1.6,mats.green);label('YADESWAR / WORK IN MOTION',4.8,.32,0,2.35,1.603,33);
const hit=[];['THREADLY','STOCKFLOW','TAARA'].forEach((t,i)=>{const x=-2.65+i*2.65;box(2.34,1.85,.13,x,.95,1.44,mats.dark);const shutter=box(2.13,1.45,.08,x,1.08,1.53,new THREE.MeshStandardMaterial({color:0x687b69,roughness:.75}));shutter.userData.id=['threadly','stockflow','taara'][i];hit.push(shutter);for(let y=.45;y<1.8;y+=.12)box(2.12,.023,.025,x,y,1.58,mats.roof);label('0'+(i+1)+'  /  '+t,1.7,.23,x,1.79,1.6,38);box(2.35,.13,.65,x,.045,1.85,mats.concrete);[-1,1].forEach(s=>{cyl(.06,.48,x+s*1.05,.26,1.98,mats.wood);box(.13,.08,.13,x+s*1.05,.43,1.98,mats.dark)})});
// Parcels and pallets at the loading apron.
for(let j=0;j<2;j++){const x=-3.65+j*.62;box(.55,.08,.65,x,.09,2.55,mats.wood);for(let k=0;k<2;k++){box(.47,.34,.48,x,.3+k*.35,2.55,mats.box);box(.06,.345,.486,x,.3+k*.35,2.55,mats.wood)}}
// Green delivery truck, assembled as real 3D geometry.
const truck=new THREE.Group();model.add(truck);truck.position.set(2.8,0,2.55);box(2.15,.14,.92,0,.38,0,mats.dark,truck);box(1.35,1.12,1,-.34,1,0,mats.ivory,truck);box(.74,.82,.94,.74,.84,0,mats.green,truck);box(.045,.35,.75,1.12,1.06,0,mats.glass,truck);box(.48,.31,.015,.75,1.05,.477,mats.glass,truck);box(.48,.31,.015,.75,1.05,-.477,mats.glass,truck);box(.12,.16,.98,1.15,.43,0,mats.white,truck);for(const x of [-.7,.75])for(const z of [-.51,.51]){const wheel=cyl(.24,.12,x,.29,z,mats.black,truck);wheel.rotation.x=Math.PI/2;const hub=cyl(.105,.126,x,.29,z,mats.concrete,truck);hub.rotation.x=Math.PI/2}label('GY',.64,.34,-.35,1.08,.505,80,truck);
// Small rooftop skylights and a vent, with believable roof detail.
box(1.2,.09,.8,-1.8,2.94,-.5,mats.glass);box(1.2,.09,.8,.2,2.94,-.5,mats.glass);box(.5,.3,.5,2.4,3,-1,mats.concrete);for(let j=0;j<5;j++)box(.4,.025,.025,2.4,2.9+j*.045,-.742,mats.dark);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.12}));floor.rotation.x=-Math.PI/2;floor.position.y=-.27;floor.receiveShadow=true;scene.add(floor);model.rotation.y=-.17;
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let hovered=null,px=0,py=0;function pick(e){const r=el.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(hit)[0]?.object}el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();px=(e.clientX-r.left)/r.width-.5;py=(e.clientY-r.top)/r.height-.5;const obj=pick(e);if(hovered)hovered.material.emissive.setHex(0);hovered=obj;if(obj)obj.material.emissive.setHex(0x263e20);el.style.cursor=obj?'pointer':'default'});el.addEventListener('pointerleave',()=>{px=py=0;if(hovered)hovered.material.emissive.setHex(0);hovered=null});el.addEventListener('click',e=>{const obj=pick(e);if(obj)document.querySelector(`[data-story="${obj.userData.id}"]`).click()});const reduced=matchMedia('(prefers-reduced-motion: reduce)');function resize(){const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.position.set(6,7.5,19);camera.position.multiplyScalar(w/h<1.1?1.3:1);camera.lookAt(0,.4,0);camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(el);resize();let start=performance.now();document.querySelector('#scene-replay').onclick=()=>{start=performance.now()};let visible=true, firstReveal=true;new IntersectionObserver(e=>{visible=e[0].isIntersecting;if(visible&&firstReveal){start=performance.now();firstReveal=false}}).observe(el);function animate(now){requestAnimationFrame(animate);if(!visible)return;const elapsed=now-start-700;
const entrance=Math.min(Math.max(elapsed/2100,0),1);
const arrival=Math.min(Math.max((elapsed-650)/2500,0),1);
const ease=t=>1-Math.pow(1-t,3);
truck.position.x=reduced.matches?2.6:2.6+8*(1-ease(arrival));
model.position.x=reduced.matches?0:4.5*(1-ease(entrance));
model.rotation.y=reduced.matches?.12:-.65+.77*ease(entrance)+px*.08*entrance;
model.rotation.x=reduced.matches?0:-py*.025*entrance;renderer.render(scene,camera)}requestAnimationFrame(animate)}warehouse().catch(e=>{console.warn('3D scene unavailable',e);document.querySelector('#scene-fallback').hidden=false});
